version: '3'
services:
  postgres:
    image: postgres:9.5
    container_name: wallet3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    volumes:
      - ./init.sql:/docker-entrypoint-db.d/init.sql